# Generated by Django 4.0.3 on 2022-03-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100)),
                ('invoice_number', models.TextField()),
                ('customer_address', models.TextField(blank=True)),
                ('customer_city_state', models.TextField(blank=True)),
                ('customer_cntry', models.TextField(blank=True)),
                ('customer_name', models.TextField()),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('salesperson_address', models.TextField(blank=True)),
                ('salesperson_city_state', models.TextField(blank=True)),
                ('salesperson_cntry', models.TextField(blank=True)),
                ('salesperson_company', models.TextField(blank=True)),
                ('salesperson_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('taxtotal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('terms', models.TextField(blank=True, max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('line_items', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
